### ISSUE TITLE
Support creating a sensor template

### ISSUE THREAD

**Issue by marcofl** [HomeDicator/HomeDicator-Templates#2]
Hi, does anyone know how to create a sensor widget that changes the color based on value thresholds? I'm just getting started with lvgl, don't fully understand yet how it works.

I tried something like this:

HomeDicator/core/templates/threshold_sensor.yaml
```
platform: homeassistant
id: ${hass_sensor_id}
entity_id: sensor.${hass_sensor_id}
recolor: true
on_value:
  - lvgl.label.update:
      id: lvgl_value_label_${hass_sensor_id}
      text: !lambda |-
        char buffer[10];
        snprintf(buffer, sizeof(buffer), "%.1f", x);
        return buffer;
      bg_color: !lambda |-
        lv_color_t color;
        if (x <= ${threshold_low}) {
          color = lv_color_hex(0x0000FF);  // Blue
        } else if (x <= ${threshold_medium}) {
          color = lv_color_hex(0x00FF00);  // Green
        } else if (x <= ${threshold_high}) {
          color = lv_color_hex(0xFFFF00);  // Yellow
        } else {
          color = lv_color_hex(0xFF0000);  // Red
        }
        return color;
```

and then 
```
  - !include
      file: HomeDicator/core/templates/threshold_sensor.yaml
      vars:
        hass_sensor_id: "homedicator_co2_level" # sensor.homedicator_co2_level (RP2040)
        threshold_low: 600
        threshold_medium: 800
        threshold_high: 1400
```

but that doesn't seem to do the trick. any ideas? thanks a lot.
